sudo: required
language: node_js
services:
  - docker
node_js:
  - '12'

before_install:
  - nvm install-latest-npm

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - APM_SERVER_PORT=8200
    - APM_SERVER_URL=http://localhost:8001
    - MODE=none
    - DISPLAY=:0

stages:
  - check
  - test

jobs:
  allow_failures:
    - script: npm run bundlesize
  include:
    - stage: check
      script: npm run lint
      name: 'Lint'
    - stage: check
      script: npm run bundlesize
      name: 'Analyse size of JS bundles'
    - stage: test
      env:
        - STACK_VERSION=8.0.0-SNAPSHOT
        - SCOPE=@elastic/apm-rum-core
    - stage: test
      env:
        - STACK_VERSION=8.0.0-SNAPSHOT
        - SCOPE=@elastic/apm-rum
    - stage: test
      env:
        - STACK_VERSION=8.0.0-SNAPSHOT
        - SCOPE=@elastic/apm-rum-react
    - stage: test
      env:
        - STACK_VERSION=8.0.0-SNAPSHOT
        - SCOPE=@elastic/apm-rum-angular
    - stage: test
      env:
        - STACK_VERSION=8.0.0-SNAPSHOT
        - SCOPE=@elastic/apm-rum-vue
addons:
  apt:
    packages:
      - xsltproc
      - libxml2-utils

script:
  - docker-compose -f ./dev-utils/docker-compose.yml up -d wait-for-apm-server
  - npm run test
