sudo: required
language: node_js
services:
  - docker
node_js:
- '8'
env:
  global:
  - SAUCE_USERNAME=elastic-apm-base
  - SAUCE_ACCESS_KEY=4b6720f1-ecdc-448d-85be-ebf947e14507
  - APM_SERVER_PORT=8001
  - APM_SERVER_URL=http://localhost:8001
  - MODE=saucelabs
  matrix:
  - STACK_VERSION=6.5.0
  - STACK_VERSION=6.6.0
  - STACK_VERSION=7.0.0-alpha1-SNAPSHOT
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
     - xsltproc
     - libxml2-utils
before_install:
  - docker-compose -f ./test/docker-compose.yml up -d apm-server
  