codecov:
  notify:
    require_ci_to_pass: no
comment:
  layout: "header, changes, diff, files"
  behavior: default
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1
    patch:
      default:
        target: auto
