codecov:
  notify:
    require_ci_to_pass: yes
comment:
  layout: "header, changes, diff, files"
  behavior: default
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1
      rum:
        - packages/rum
      rum-core:
        - packages/rum-core
      rum-react:
        - packages/rum-react
    patch:
      default:
        target: auto
