#!/bin/bash

if [[ "$SCOPE" == "@elastic/apm-rum" ]];
then
    export SAUCE_USERNAME=elastic-apm-base
    export SAUCE_ACCESS_KEY=4b6720f1-ecdc-448d-85be-ebf947e14507
else
    export SAUCE_USERNAME=elastic-apm
    export SAUCE_ACCESS_KEY=8e8b688d-cee9-4a7b-9fd4-bb4e01f0421c
fi


echo "Sauce account: $SAUCE_USERNAME"