[[advanced-topics]]
== Advanced Topics

* <<custom-transactions, Custom Transactions>>
* <<custom-transaction-name, Initial page load transaction names>>
* <<longtasks>>
* <<typescript>>

[[longtasks]]
=== How to interpret Longtask Spans in the UI

Longtasks is a new performance metric that helps measure the responsiveness and
helps understand the bad user experience on the web. It enables detecting tasks
that monopolize the UI thread for extended periods (greater than 50 milliseconds) and block other
critical tasks from being executed as stated in the official spec[https://github.com/w3c/longtasks].

RUM agent automatically captures these Longtasks and include them as Spans as
part of the transaction. Since Longtasks currently does not have the full information on
which part of code cause slowness, it would be hard to interpret these spans.
Some tips below would interpret these spans in a meaningful way

+ Name of the Longtask span could be `self`, `same-origin`, etc. would imply the
  origin of the task. It could be the current browsing context or inside iframes.

+ Context of the span is enriched with useful information like `attribution`
  (the type of work such as script, layout, etc), `type`, `id` and `name` which
  determines the culprit container(such as window, iframe, embed or object)
  responsible for the long task

With the help of the transaction timeline and the span timings, one could dig
deeper by marking the slow application code using User Timing
API[https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark]
which would be again captured as Spans by the agent and combining them along with Longtasks would
reveal the true source code location.

[[typescript]]
=== Using with TypeScript

RUM agent publishes the type definitions for the `@elastic/apm-rum` package via `types` property in `package.json`.
If you are importing the package on a TypeScript codebase, you will get automatic code completion, hover info
and method signature information on supported platforms (Visual Studio Code, etc)


include::./custom-transactions.asciidoc[Custom Transactions]
include::./custom-transaction-name.asciidoc[Initial page load transaction names]
