[[distributed-tracing-guide]]
== Distributed Tracing

If you use a distributed architecture for your application, you can use our distributed tracing feature to monitor
traces through out your application. Distributed tracing is enabled by default in the RUM agent, however, 
it only includes request made to the same origin. In order to include cross-origin 
requests you need to set `distributedTracingOrigins` configuration option.


For example let's consider an application that is served from `https://example.com`, 
by default all the http requests made to `https://example.com` 
will be included in the trace. To include requests made to `https://api.example.com` 
you need to add the following configuration:


[source,js]
----
var apm = initApm({
  ...
  distributedTracingOrigins: ['https://api.example.com']
})
----


This effectively tells the agent to add the distributed tracing http header (`elastic-apm-traceparent`) 
to requests made to `https://api.example.com`.

[float]
[[server-configuration]]
=== Server configuration

The RUM agent is only one of the components in a distributed trace, therefore,
you need to properly configure other components in order to use distributed tracing.
In our example above you need to make sure `https://api.example.com` 
can respond to requests that include distributed tracing header.

Specifically, `https://api.example.com` will receive an `OPTIONS` request with the following headers:


----
Access-Control-Request-Headers: elastic-apm-traceparent
Access-Control-Request-Method: [request-method]
Origin: [request-origin]
----

And should respond to it with these headers:

----
Access-Control-Allow-Headers: elastic-apm-traceparent
Access-Control-Allow-Methods: [allowed-methods]
Access-Control-Allow-Origin: [request-origin]
----

NOTE: `Access-Control-Request-Headers` might include more headers than just `elastic-apm-traceparent` 
and the response should include all of them if the server wishes to let the browser send the original request.

To read more about cross-origin requests and why this process is necessary
 please see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS[Cross-Origin Resource Sharing].


NOTE: To make sure all components in a distributed trace are included,
 the sampling rate of backend agents might be affected by the sampling rate of the RUM agent.
