[[intro]]
== Introduction

Welcome to the APM Real User Monitoring (RUM) JavaScript Agent documentation.

The Elastic APM RUM JavaScript agent sends performance metrics and errors to the APM Server.

NOTE: The APM JavaScript agent is compatible with APM Server v6.5+.

[float]
[[additional-components]]
=== Additional Components

APM Agents work in conjunction with the {apm-server-ref-v}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
Please view the {apm-overview-ref-v}/index.html[APM Overview] for details on how these components work together.

You will also need to {apm-server-ref-v}/rum.html[enable frontend endpoints in the `apm-server` configuration].

[[getting-started]]
== Getting started

Install the APM agent for JavaScript as a dependency to your application:

[source,bash]
----
npm install elastic-apm-js-base --save
----

Configure the agent:

[source,js]
----
import { init as initApm } from 'elastic-apm-js-base'
var apm = initApm({
  
  // Set required service name (allowed characters: a-z, A-Z, 0-9, -, _, and space)
  serviceName: '',

  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: 'http://localhost:8200',
  
  // Set service version (required for sourcemap feature)
  serviceVersion: ''
})
----

Alternatively, you can use a script element and the `elasticApm` global object to load and initialize the agent:

[source,html]
----
<script src="elastic-apm-js-base/dist/bundles/elastic-apm-js-base.umd.min.js"></script>
<script>
  elasticApm.init({
    serviceName: '',
    serverUrl: 'http://localhost:8200',
  })
</script>
----

NOTE: Currently our minified JavaScript bundle is about 15KB (gzipped).
