[[intro]]
== Introduction

The Elastic APM Real User Monitoring (RUM) JavaScript Agent provides detailed performance metrics and error tracking of your web applications.
It has built-in support for popular platforms and frameworks, and an API for custom instrumentation.

The Agent also supports <<distributed-tracing-guide,distributed tracing>> for all outgoing requests.
This enables you to analyze performance throughout your microservice architecture -- all in one view.

[float]
[[features]]
=== Features

The agent uses browser timing APIs such as https://w3c.github.io/navigation-timing/[Navigation Timing]
https://w3c.github.io/resource-timing/[Resource Timing], https://w3c.github.io/paint-timing/[Paint Timing], https://w3c.github.io/user-timing/[User Timing], etc., and
captures the following information:

* <<page-load-metrics,Page load metrics>>
* Load time of Static Assets (JS, CSS, images, fonts, etc.)
* API requests (XMLHttpRequest and Fetch)
* Single page application navigations
* <<user-interactions, User interactions>> (click events that trigger network activity)
* <<user-centric-metrics, User-centric metrics>> (Long tasks, FCP, LCP, FID, etc.)
* Page information (URLs visited and referrer)
* Network connection information
* JavaScript errors
* <<<<distributed-tracing-guide, Distributed tracing>>
* <<breakdown-metrics-docs, Breakdown metrics>>

[float]
[[additional-components]]
=== Additional Components

APM Agents work in conjunction with the {apm-server-ref-v}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
The {apm-overview-ref-v}/index.html[APM Overview] provides details on how these components work together,
and provides a matrix outlining {apm-overview-ref-v}/agent-server-compatibility.html[Agent and Server compatibility].

include::./set-up.asciidoc[]
