[[intro]]
== Introduction

Welcome to the APM Real User Monitoring (RUM) JavaScript Agent documentation.

The Elastic APM RUM JavaScript agent sends performance metrics and errors to the APM Server.
The agent is only one of multiple components you need to get started with APM.
Please also have a look at the documentation for

 * {apm-server-ref}[APM Server]
 ** APM JavaScript agent is compatible with APM Server v6.3+.
 ** {apm-server-ref}/rum.html[enable frontend endpoints in the apm-server configuration].
 * {ref}[Elasticsearch]


[[getting-started]]
== Getting started

Install the APM agent for JavaScript as a dependency to your application:

[source,bash]
----
npm install elastic-apm-js-base --save
----

Configure the agent:

[source,js]
----
import { init as initApm } from 'elastic-apm-js-base'
var apm = initApm({
  
  // Set required service name (allowed characters: a-z, A-Z, 0-9, -, _, and space)
  serviceName: '',

  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: 'http://localhost:8200',
  
  // Set service version (required for sourcemap feature)
  serviceVersion: ''
})
----

Alternatively, you can use a script element and the `elasticApm` global object to load and initialize the agent:

[source,html]
----
<script src="elastic-apm-js-base/dist/bundles/elastic-apm-js-base.umd.min.js"></script>
<script>
  elasticApm.init({
    serviceName: '',
    serverUrl: 'http://localhost:8200',
  })
</script>
----

NOTE: Currently our minified JavaScript bundle is about 15KB (gzipped).
