[[troubleshooting]]
== Troubleshooting

[float]
[[errors-originating-from-agent]]
=== Some errors in the application appear to be originating from the agent's JavaScript file
In some cases when you look at the stack trace of an error, it appears to be originating from
the agent's JavaScript file. However, since we need to patch some browser APIs in order to provide
some of the core functionalities of the agent, our JavaScript file appears in the error stack trace.
Often, the error is generated from another part your application, you can follow the stack trace
further to identify the offending code.


Of course, there are errors that might have been caused by the agent itself and we appreciate it if
you <<get-in-touch, report them back to us>>.


[float]
[[no-stack-trace-available]]
=== No stack trace available in the Span detail view
The RUM JS agent does not support stack traces for spans due to performance concerns related to gathering stack information.

[float]
[[debugging]]
=== Debugging

In order to debug the agent consider performing the following steps:

1. Add `logLevel: 'debug'` to the agent configuration
2. Reload the application
3. Wait at least 5 seconds after the page has loaded
4. Monitor the Console and Network panel in your browsers developer tools

[float]
[[disable-events-payload-compression]]
=== Disable events payload compression

In browsers such as Chrome the payload of the events sent by the RUM JS agent is being compressed with gzip.
Because of that, you will not see a readable content when inspecting the event with the Network panel of your browser developer tools.

There are situations where that can be an issue. For instance, HAR files will not show a readable information. Therefore, inspecting events
for debugging purposes will not be possible.

There are two ways to disable the payload compression:

1. Creating an item named `_elastic_inspect_beacon_` using the sessionStorage browser API.
2. Loading the webpage including the query param `_elastic_inspect_beacon_` in the URL. E.g. `https://elastic.co?_elastic_inspect_beacon_`

The effect of this will remain until the tab or browser is closed.

[float]
[[disable-agent]]
=== Disable the Agent

In the unlikely event the agent causes disruptions to a production application,
you can disable the agent while you troubleshoot.

To disable the agent, set <<active,`active`>> to `false`.

[float]
[[get-in-touch]]
=== Get in touch

If you have any questions, please create a new topic in the https://discuss.elastic.co/c/apm[Elastic APM discuss forum].

For bug reports and feature requests, please https://github.com/elastic/apm-agent-rum-js/issues/new[create an issue] on our https://github.com/elastic/apm-agent-rum-js[github repo]
and include as much information as possible. See <<debugging, Debugging>> for how to gather debugging information.
