name: test

on:
  pull_request:
    # Don't trigger if it's only docs files
    paths:
      - "**"
      - "!**/*.asciidoc"
      - "!*/*.md"

# Probably needs to be moved to inputs?
env:
  GOAL: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Lint
        run: .ci/scripts/lint.sh
      - name: Bundle Size
        continue-on-error: true
        run: |
          npm run bundlesize
  puppeteer:
    strategy:
      matrix:
        elastic-stack-version:
          - 8.0.0-SNAPSHOT
          - 8.5.1
        scope:
          - "@elastic/apm-rum"
          - "@elastic/apm-rum-core"
          - "@elastic/apm-rum-react"
          - "@elastic/apm-rum-angular"
          - "@elastic/apm-rum-vue"
    runs-on: ubuntu-latest
    name: ${{ matrix.scope }} - ${{ matrix.elastic-stack-version }}
    env:
      STACK_VERSION: ${{ matrix.elastic-stack-version }}
      SCOPE: ${{ matrix.scope }}
      APM_SERVER_URL: http://apm-server:8200
      KIBANA_URL: http://kibana:5601
      APM_SERVER_PORT: 8200
    steps:
      - name: Pull and build docker infra
        run: .ci/scripts/pull_and_build.sh
      - name: Run tests
        run: .ci/scripts/test.sh
